### ISSUE TITLE
What's the purpose of the old_url header field?

### ISSUE THREAD

**Issue by fam2342** [theobald-software/theobald-software.github.io#64]
Example:
https://raw.githubusercontent.com/theobald-software/theobald-software.github.io/master/content/_en/board-connector/index.md
contains an `old_url: /BOARD-Connector-EN/` but https://help.theobald-software.com/BOARD-Connector-EN/ leads to a 404 (and a meta-refresh that "redirects" to the 404 page).

**Comment by ErwinLengkeek** [comment]
The old_url field was introduced to match pages from the old Online Help to this new Online Help system. Once the user goes to an old url because of a bookmark or old reference on another website, the user will see a 404 page. However, we detect what the original url was, match it against the old_url and display a text along the lines of:

> The page you wanted to see has changed, just like our Help Portal! Were you looking for "BoardConnector"?

The text contains the link to the new page. Jekyll does not allow rewriting of url's or permanent redirects in our particular case with the structure of the old url's. The old_url field is only necessary for all existing content and will eventually become redundant as well, given enough time has passed.

**Comment by fam2342** [comment]
OK, I understand. I didn't see the text because it's provided through a third-party URL (blocked by default in my browser).
What shame that GitHub pages doesn't have an option to configure proper redirects on HTTP level.
